# Generated by Django 5.2.5 on 2025-08-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_stuff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='topic',
            new_name='topics',
        ),
    ]
