# Generated by Django 5.2.5 on 2025-08-24 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_stuff', '0002_rename_topic_entry_topics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='topics',
            new_name='topic',
        ),
    ]
